display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      fields:
        name:
          separator: ', '
        price__number:
          separator: ', '
        quantity:
          separator: ', '
        price_components:
          separator: ', '
      arguments:
        id:
          exception:
            title: Alle
  block_1:
    display_title: Block
