name: Train Base
type: module
description: Store all base classes for trains
core: 8.x
package: Trains
dependencies:
  - content_translation
  - master
  - plugin
  - address
  - geolocation
  - currency
