train_base.train_lists:
  path: '/admin/trains'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
  requirements:
    _permission: 'access administration pages'
