name: Config tools git configuration
type: module
description: 'Stores configuration in a git repository.'
package: Configuration
# version: VERSION
# core: 8.x
configure: git_config.settings
dependencies:
  - config_files
  - config_tools


# Information added by Drupal.org packaging script on 2017-05-25
version: '8.x-1.0-alpha4'
core: '8.x'
project: 'config_tools'
datestamp: 1495734492
