display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      fields:
        redirect_source__path:
          label: Ab
          separator: ', '
        created:
          label: 'Erstellt am'
      filters:
        redirect_source__path:
          expose:
            label: Ab
        redirect_redirect__uri:
          expose:
            label: An
        language:
          expose:
            label: Originalsprache
  page_1:
    display_title: Seite
