alternativeSigns: {  }
currencyCode: SGD
currencyNumber: '702'
label: SGD
roundingStep: 0.01
sign: S$
subunits: 100
status: true
usages:
  -
    start: '1967-06-12'
    end: null
    countryCode: SG
uuid: 367b27b1-1832-4c57-bdd3-97fcdc3727e7
