alternativeSigns: {  }
currencyCode: CNY
currencyNumber: '156'
label: CNY
roundingStep: 0.01
sign: ¥
subunits: 100
status: true
usages:
  -
    start: '1953-03-01'
    end: null
    countryCode: CN
uuid: ff69951e-e278-4ba4-9ca6-59637c095fe7
