alternativeSigns: {  }
currencyCode: GBP
currencyNumber: '826'
label: GBP
roundingStep: 0.01
sign: £
subunits: 100
status: true
usages:
  -
    start: '1694-07-27'
    end: null
    countryCode: GB
  -
    start: '1830-01-01'
    end: null
    countryCode: GG
  -
    start: '1908-01-01'
    end: null
    countryCode: GS
  -
    start: '1800-01-01'
    end: '1922-01-01'
    countryCode: IE
  -
    start: '1840-01-03'
    end: null
    countryCode: IM
  -
    start: '1965-11-08'
    end: null
    countryCode: IO
  -
    start: '1837-01-01'
    end: null
    countryCode: JE
  -
    start: '1889-01-19'
    end: '1958-01-01'
    countryCode: SD
  -
    start: '1808-11-30'
    end: '1966-02-04'
    countryCode: SL
  -
    start: '1833-01-01'
    end: '1959-01-01'
    countryCode: VG
uuid: 3ba4d3fd-58d2-41c9-97d3-62ae0e347c14
