alternativeSigns: {  }
currencyCode: EUR
currencyNumber: '978'
label: EUR
roundingStep: 0.01
sign: €
subunits: 100
status: true
usages:
  -
    start: '1999-01-01'
    end: null
    countryCode: AD
  -
    start: '1999-01-01'
    end: null
    countryCode: AT
  -
    start: '1999-01-01'
    end: null
    countryCode: AX
  -
    start: '1999-01-01'
    end: null
    countryCode: BE
  -
    start: '1999-01-01'
    end: null
    countryCode: BL
  -
    start: '2003-02-04'
    end: '2006-06-03'
    countryCode: CS
  -
    start: '2008-01-01'
    end: null
    countryCode: CY
  -
    start: '1999-01-01'
    end: null
    countryCode: DE
  -
    start: '2011-01-01'
    end: null
    countryCode: EE
  -
    start: '1999-01-01'
    end: null
    countryCode: ES
  -
    start: '1999-01-01'
    end: null
    countryCode: FI
  -
    start: '1999-01-01'
    end: null
    countryCode: FR
  -
    start: '1999-01-01'
    end: null
    countryCode: GF
  -
    start: '1999-01-01'
    end: null
    countryCode: GP
  -
    start: '2001-01-01'
    end: null
    countryCode: GR
  -
    start: '1999-01-01'
    end: null
    countryCode: IE
  -
    start: '1999-01-01'
    end: null
    countryCode: IT
  -
    start: '1999-01-01'
    end: null
    countryCode: LU
  -
    start: '2014-01-01'
    end: null
    countryCode: LV
  -
    start: '1999-01-01'
    end: null
    countryCode: MC
  -
    start: '2002-01-01'
    end: null
    countryCode: ME
  -
    start: '1999-01-01'
    end: null
    countryCode: MF
  -
    start: '1999-01-01'
    end: null
    countryCode: MQ
  -
    start: '2008-01-01'
    end: null
    countryCode: MT
  -
    start: '1999-01-01'
    end: null
    countryCode: NL
  -
    start: '1999-01-01'
    end: null
    countryCode: PM
  -
    start: '1999-01-01'
    end: null
    countryCode: PT
  -
    start: '1999-01-01'
    end: null
    countryCode: EU
  -
    start: '1999-01-01'
    end: null
    countryCode: RE
  -
    start: '2007-01-01'
    end: null
    countryCode: SI
  -
    start: '2009-01-01'
    end: null
    countryCode: SK
  -
    start: '1999-01-01'
    end: null
    countryCode: SM
  -
    start: '1999-01-01'
    end: null
    countryCode: TF
  -
    start: '1999-01-01'
    end: null
    countryCode: VA
  -
    start: '1999-01-01'
    end: null
    countryCode: YT
uuid: 3510b1ea-9b0a-4f94-b787-35abcfc0dbc3
