abs_urls: false
roles_profiles:
  administrator:
    public: admin
  agent:
    public: admin
  content_manager:
    public: admin
_core:
  default_config_hash: 6Wk4BLqlH9PdR3lPJohO4Ek3-uRJAgdfrVT4qWYXVMY
