session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    ru: ru
    es: es
    pt: pt
    it: it
    fr: fr
    de: de
  domains:
    en: ''
    ru: ''
    es: ''
    pt: ''
    it: ''
    fr: ''
    de: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
