label: 'Главная страница'
tags:
  title: 'Купить билеты на поезд онлайн | Rail.Ninja'
  keywords: 'rail ninja, rail.ninja. railninja, купить билеты на поезд'
  description: 'Rail.Ninja предлагает курируемый экспертами сервис по поиску и покупке билетов на поезда по всей Европе'
  abstract: 'Rail.Ninja предлагает курируемый экспертами сервис по поиску и покупке билетов на поезда по всей Европе'
  og_description: 'Rail.Ninja предлагает курируемый экспертами сервис по поиску и покупке билетов на поезда по всей Европе'
