display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        id:
          label: ID
          separator: ', '
        number:
          separator: ', '
        status:
          label: Estado
          separator: ', '
        hash:
          label: Hash
          separator: ', '
        owner:
          label: Propietario
          separator: ', '
        order_total__number:
          separator: ', '
        operations:
          label: 'Enlaces de operación'
  page_1:
    display_title: Página
