display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_asc_label: Asc
          sort_desc_label: Disc
      fields:
        name:
          separator: ', '
        price__number:
          separator: ', '
        quantity:
          separator: ', '
        price_components:
          separator: ', '
      arguments:
        id:
          exception:
            title: Tutti
  block_1:
    display_title: Blocco
