label: Kişiler
description: 'Sitenizle etkileşim kuran kişileri arayın ve yönetin.'
display:
  default:
    display_title: 'Ana (master)'
    display_options:
      exposed_form:
        options:
          submit_button: Süzgeç
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      pager:
        options:
          expose:
            items_per_page_label: 'Sayfa başına öğe sayısı'
            items_per_page_options_all_label: '- Tümü -'
            offset_label: 'Başlangıç değeri'
      fields:
        user_bulk_form:
          label: 'Toplu güncelleme'
        name:
          label: 'Kullanıcı Adı'
        status:
          label: Durum
          settings:
            format_custom_true: Etkin
            format_custom_false: Engellendi
        roles_target_id:
          label: Roller
        created:
          label: 'Üyelik süresi'
        access:
          label: 'Son erişim'
        operations:
          label: İşlemler
        mail:
          separator: ', '
      filters:
        status:
          group_info:
            label: Durum
            group_items:
              1:
                title: Etkin
              2:
                title: Engellendi
        roles_target_id:
          expose:
            label: Rol
        permission:
          expose:
            label: İzinler
      title: Kişiler
      empty:
        area_text_custom:
          content: 'Hiç kimse mevcut değil.'
      use_more_text: 'daha fazla'
  page_1:
    display_title: Sayfa
    display_options:
      menu:
        title: Listele
        description: 'Sitenizle etkileşim kuran kişileri arayın ve yönetin.'
      tab_options:
        title: Kişiler
        description: 'Kullanıcı hesapları, roller ve izinleri yönetin.'
