display:
  default:
    display_title: 'Ana (master)'
    display_options:
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      filters:
        access:
          expose:
            label: 'Son erişim'
            description: 'Bir kullanıcı son sayfa ziyaretinden itibaren bu kadar süre boyunca çevrim içi olarak kabul edilir.'
      title: 'Kimler çevrim içi'
  who_s_online_block:
    display_title: 'Kimler çevrim içi'
    display_options:
      block_description: 'Kimler çevrim içi'
