label: 'Ana sayfa'
display:
  default:
    display_options:
      empty:
        area_text_custom:
          content: 'Henüz bir ana sayfa içeriği oluşturulmadı.'
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      pager:
        options:
          expose:
            items_per_page_label: 'Sayfa başına öğe sayısı'
            items_per_page_options_all_label: '- Tümü -'
            offset_label: 'Başlangıç değeri'
    display_title: 'Ana (master)'
  feed_1:
    display_title: Besleme
  page_1:
    display_title: Sayfa
