label: Arşiv
display:
  default:
    display_title: 'Ana (master)'
    display_options:
      title: 'Aylık arşiv'
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      pager:
        options:
          expose:
            items_per_page_label: 'Sayfa başına öğe sayısı'
            items_per_page_options_all_label: '- Tümü -'
            offset_label: 'Başlangıç değeri'
          tags:
            previous: ‹‹
            next: ››
  block_1:
    display_title: Blok
  page_1:
    display_title: Sayfa
