display:
  default:
    display_title: 'Ana (master)'
    display_options:
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      fields:
        name:
          separator: ', '
        price__number:
          separator: ', '
        quantity:
          separator: ', '
        price_components:
          separator: ', '
      arguments:
        id:
          exception:
            title: Tümü
  block_1:
    display_title: Blok
