label: İçerik
description: 'İçeriği bul ve yönet.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Süzgeç
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      fields:
        title:
          label: Başlık
        type:
          label: 'İçerik türü'
          separator: ', '
        name:
          label: Yazar
        status:
          label: Durum
          settings:
            format_custom_true: Yayında
            format_custom_false: 'Yayında değil'
        changed:
          label: Güncellendi
        operations:
          label: İşlemler
      filters:
        title:
          expose:
            label: Başlık
        type:
          expose:
            label: 'İçerik türü'
        status:
          expose:
            label: Durum
          group_info:
            group_items:
              1:
                title: Yayında
              2:
                title: 'Yayında değil'
        langcode:
          expose:
            label: Dil
      title: İçerik
      empty:
        area_text_custom:
          content: 'Hiçbir içerik mevcut değil.'
    display_title: 'Ana (master)'
  page_1:
    display_options:
      menu:
        title: İçerik
      tab_options:
        title: İçerik
    display_title: Sayfa
