label: 'Son yorumlar'
display:
  default:
    display_title: 'Ana (master)'
    display_options:
      title: 'Son yorumlar'
      empty:
        area_text_custom:
          content: 'Yorum mevcut değil.'
  block_1:
    display_title: Blok
    display_options:
      block_description: 'Son yorumlar'
