display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        id:
          label: 'Identifiant (ID)'
          separator: ', '
        number:
          separator: ', '
        status:
          label: Statut
          separator: ', '
        hash:
          label: Hachage
          separator: ', '
        owner:
          label: Propriétaire
          separator: ', '
        order_total__number:
          separator: ', '
        operations:
          label: 'Liens d''actions'
  page_1:
    display_title: Page
