<?php

/**
 * @file
 * Contains rn_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rn_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rn_field module.
    case 'help.page.rn_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains custom field types, field widgets, field formatters and all related logic') . '</p>';
      return $output;

    default:
  }
}
