name: Config tools active configuration files
type: module
description: 'Allows you to specify an active file directory to save current configuration.'
package: Configuration
# version: VERSION
# core: 8.x
configure: config_files.settings

# Information added by Drupal.org packaging script on 2017-05-25
version: '8.x-1.0-alpha4'
core: '8.x'
project: 'config_tools'
datestamp: 1495734492
