salesforce.credentials:
  type: config_object
  mapping:
    consumer_key:
      type: string
      label: Consumer key
    consumer_secret:
      type: string
      label: Consumer secret
    endpoint:
      type: string
      label: Endpoint
    refresh_token:
      type: string
      label: Refresh token
    instance_url:
      type: string
      label: Instance URL
