alternativeSigns: {  }
currencyCode: NOK
currencyNumber: '578'
label: 'Norwegian krone'
roundingStep: 0.01
sign: kr
subunits: 100
status: true
usages:
  -
    start: '1905-06-07'
    end: null
    countryCode: BV
  -
    start: '1905-06-07'
    end: null
    countryCode: 'NO'
  -
    start: '1905-06-07'
    end: null
    countryCode: SJ
uuid: 2be99a1e-82f3-4d8b-826e-b0437f84b20d
