alternativeSigns: {  }
currencyCode: XXX
currencyNumber: '999'
label: 'No currency'
roundingStep: null
sign: ¤
subunits: 0
status: true
usages:
  -
    start: ''
    end: ''
    countryCode: AQ
  -
    start: ''
    end: ''
    countryCode: ZZ
uuid: 44ada996-4365-4a98-ba75-eec20dc8e3c4
