display:
  default:
    display_title: Główny
    display_options:
      exposed_form:
        options:
          submit_button: Zastosuj
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Pierwsza'
            last: 'Ostatnia »'
          expose:
            items_per_page_label: 'Elementów na stronę'
            items_per_page_options_all_label: '- Wszystko -'
            offset_label: Przesunięcie
      fields:
        id:
          label: ID
          separator: ', '
        number:
          separator: ', '
        status:
          label: Status
          separator: ', '
        hash:
          label: Hasz
          separator: ', '
        owner:
          label: Właściciel
          separator: ', '
        order_total__number:
          separator: ', '
        operations:
          label: 'Odnośniki do czynności'
  page_1:
    display_title: Strona
