display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        name:
          separator: ', '
        price__number:
          separator: ', '
        quantity:
          separator: ', '
        price_components:
          separator: ', '
      arguments:
        id:
          exception:
            title: Todo
  block_1:
    display_title: Bloque
