display:
  default:
    display_title: 主
    display_options:
      exposed_form:
        options:
          submit_button: 应用
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      fields:
        name:
          separator: '， '
        price__number:
          separator: '， '
        quantity:
          separator: '， '
        price_components:
          separator: '， '
      arguments:
        id:
          exception:
            title: 全部
  block_1:
    display_title: 区块
