<?php

/**
 * @file
 * Contains russian_trains_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function russian_trains_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the russian_trains_migration module.
    case 'help.page.russian_trains_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Russian Train Migration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function russian_trains_migration_theme() {
  return [
    'russian_trains_migration' => [
      'template' => 'russian_trains_migration',
      'render element' => 'children',
    ],
  ];
}
