alternativeSigns: {  }
currencyCode: CAD
currencyNumber: '124'
label: CAD
roundingStep: 0.01
sign: C$
subunits: 100
status: true
usages:
  -
    start: '1858-01-01'
    end: null
    countryCode: CA
uuid: b308de12-9371-44ff-add4-6d111256bb55
