alternativeSigns: {  }
currencyCode: NZD
currencyNumber: '554'
label: NZD
roundingStep: 0.01
sign: $
subunits: 100
status: true
usages:
  -
    start: '1967-07-10'
    end: null
    countryCode: CK
  -
    start: '1967-07-10'
    end: null
    countryCode: NU
  -
    start: '1967-07-10'
    end: null
    countryCode: NZ
  -
    start: '1969-01-13'
    end: null
    countryCode: PN
  -
    start: '1967-07-10'
    end: null
    countryCode: TK
uuid: f888a14c-ec4a-4ca5-a98c-5a182bd1e6ae
