alternativeSigns:
  - руб
currencyCode: RUB
currencyNumber: '643'
label: RUB
roundingStep: 0.01
sign: ₽
subunits: 100
status: true
usages:
  -
    start: '1999-01-01'
    end: null
    countryCode: RU
uuid: 4b271ad6-04cf-400e-ab7a-dabde5329c1c
