session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ru: ru
    de: de
    it: it
    fr: fr
    pt: pt
  domains:
    en: ''
    es: ''
    ru: ''
    de: ''
    it: ''
    fr: ''
    pt: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
