status: true
min_days_before_departure: 0
min_hours_before_departure: !!float 10
max_days_before_departure: 60
use_local_file: false
ignore_cache: false
long_cache:
  max_routes: '10'
  from: 0
  to: 3600
  lifetime: 72000
live: true
available_routes: null
available_stations:
  -
    departure_station: '1'
    arrival_station: '16'
    stations:
      -
        id: '2'
      -
        id: '89'
  -
    departure_station: '16'
    arrival_station: '1'
    stations:
      -
        id: '3'
      -
        id: '24'
cache:
  -
    from: '0'
    to: '60'
    lifetime: 1800
booking_available: false
